# Generated by Django 6.0.1 on 2026-01-13 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='alumno',
            fields=[
                ('id_alumno', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Ingrese tu nombre', max_length=30)),
                ('apellido_parterno', models.CharField(help_text='Apellido paterno', max_length=20)),
                ('apellido_materno', models.CharField(help_text='Apellido materno', max_length=20)),
                ('edad', models.PositiveIntegerField()),
                ('licenciatura', models.CharField(max_length=40)),
                ('correo', models.EmailField(max_length=40)),
                ('tipo_aprendizaje', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Emocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emocion', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='test',
            fields=[
                ('id_test', models.AutoField(primary_key=True, serialize=False)),
                ('emocion', models.CharField(max_length=30)),
                ('texto_generado', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('rol', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Diccionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palabra', models.CharField(max_length=10)),
                ('emocion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.emocion')),
            ],
        ),
        migrations.CreateModel(
            name='EstilosAprendizaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p1', models.CharField(max_length=1)),
                ('p2', models.CharField(max_length=1)),
                ('p3', models.CharField(max_length=1)),
                ('p4', models.CharField(max_length=1)),
                ('p5', models.CharField(max_length=1)),
                ('p6', models.CharField(max_length=1)),
                ('p7', models.CharField(max_length=1)),
                ('p8', models.CharField(max_length=1)),
                ('p9', models.CharField(max_length=1)),
                ('p10', models.CharField(max_length=1)),
                ('resultado', models.CharField(blank=True, max_length=50)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.CharField(max_length=45)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.alumno')),
                ('emocion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.emocion')),
            ],
        ),
        migrations.CreateModel(
            name='Texto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.CharField(max_length=1000)),
                ('emocion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.emocion')),
            ],
        ),
    ]
