# Generated by Django 5.2.7 on 2025-11-06 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ingrese tú nombre', max_length=30)),
                ('Apellido_parterno', models.CharField(help_text='Apellido paterno', max_length=20)),
                ('Apellido_materno', models.CharField(help_text='Apellido materno', max_length=20)),
                ('Edad', models.PositiveIntegerField()),
                ('Licenciatura', models.CharField(max_length=40)),
            ],
        ),
    ]
