# Generated by Django 6.0.1 on 2026-01-25 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='alumno',
            fields=[
                ('id_alumno', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido_paterno', models.CharField(max_length=20)),
                ('apellido_materno', models.CharField(max_length=20)),
                ('edad', models.PositiveIntegerField()),
                ('licenciatura', models.CharField(max_length=40)),
                ('tipo_aprendizaje', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
