# Generated by Django 6.0.1 on 2026-01-13 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='correo',
            field=models.EmailField(blank=True, max_length=40, null=True),
        ),
    ]
