# Generated by Django 5.2.7 on 2025-11-06 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='id',
        ),
        migrations.AddField(
            model_name='alumno',
            name='id_alumno',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
