# Generated by Django 6.0.1 on 2026-01-25 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstilosAprendizaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p1', models.CharField(max_length=1)),
                ('p2', models.CharField(max_length=1)),
                ('p3', models.CharField(max_length=1)),
                ('p4', models.CharField(max_length=1)),
                ('p5', models.CharField(max_length=1)),
                ('p6', models.CharField(max_length=1)),
                ('p7', models.CharField(max_length=1)),
                ('p8', models.CharField(max_length=1)),
                ('p9', models.CharField(max_length=1)),
                ('p10', models.CharField(max_length=1)),
                ('resultado', models.CharField(blank=True, max_length=50)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.alumno')),
            ],
        ),
    ]
