# Generated by Django 6.0.1 on 2026-01-25 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_estilosaprendizaje'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EstilosAprendizaje',
            new_name='estilos_aprendizaje',
        ),
    ]
