# Generated by Django 5.2.7 on 2025-11-06 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_alumno_id_alumno_id_alumno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id_test', models.AutoField(primary_key=True, serialize=False)),
                ('Emocion', models.CharField(max_length=30)),
                ('Texto_generado', models.CharField(max_length=1000)),
            ],
        ),
        migrations.RenameField(
            model_name='alumno',
            old_name='nombre',
            new_name='Nombre',
        ),
    ]
