# Generated by Django 6.0.1 on 2026-01-25 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_rename_estilosaprendizaje_estilos_aprendizaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estilos_aprendizaje',
            name='p1',
            field=models.CharField(choices=[('A', 'Visual'), ('B', 'Auditivo'), ('C', 'Kinestésico')], max_length=1),
        ),
        migrations.AlterField(
            model_name='estilos_aprendizaje',
            name='p10',
            field=models.CharField(choices=[('A', 'Visual'), ('B', 'Auditivo'), ('C', 'Kinestésico')], max_length=1),
        ),
        migrations.AlterField(
            model_name='estilos_aprendizaje',
            name='p2',
            field=models.CharField(choices=[('A', 'Visual'), ('B', 'Auditivo'), ('C', 'Kinestésico')], max_length=1),
        ),
        migrations.AlterField(
            model_name='estilos_aprendizaje',
            name='p3',
            field=models.CharField(choices=[('A', 'Visual'), ('B', 'Auditivo'), ('C', 'Kinestésico')], max_length=1),
        ),
        migrations.AlterField(
            model_name='estilos_aprendizaje',
            name='p4',
            field=models.CharField(choices=[('A', 'Visual'), ('B', 'Auditivo'), ('C', 'Kinestésico')], max_length=1),
        ),
        migrations.AlterField(
            model_name='estilos_aprendizaje',
            name='p5',
            field=models.CharField(choices=[('A', 'Visual'), ('B', 'Auditivo'), ('C', 'Kinestésico')], max_length=1),
        ),
        migrations.AlterField(
            model_name='estilos_aprendizaje',
            name='p6',
            field=models.CharField(choices=[('A', 'Visual'), ('B', 'Auditivo'), ('C', 'Kinestésico')], max_length=1),
        ),
        migrations.AlterField(
            model_name='estilos_aprendizaje',
            name='p7',
            field=models.CharField(choices=[('A', 'Visual'), ('B', 'Auditivo'), ('C', 'Kinestésico')], max_length=1),
        ),
        migrations.AlterField(
            model_name='estilos_aprendizaje',
            name='p8',
            field=models.CharField(choices=[('A', 'Visual'), ('B', 'Auditivo'), ('C', 'Kinestésico')], max_length=1),
        ),
        migrations.AlterField(
            model_name='estilos_aprendizaje',
            name='p9',
            field=models.CharField(choices=[('A', 'Visual'), ('B', 'Auditivo'), ('C', 'Kinestésico')], max_length=1),
        ),
    ]
