# Generated by Django 5.2.7 on 2025-11-08 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_test_rename_nombre_alumno_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumno',
            old_name='Apellido_materno',
            new_name='apellido_materno',
        ),
        migrations.RenameField(
            model_name='alumno',
            old_name='Apellido_parterno',
            new_name='apellido_parterno',
        ),
        migrations.RenameField(
            model_name='alumno',
            old_name='Edad',
            new_name='edad',
        ),
        migrations.RenameField(
            model_name='alumno',
            old_name='Licenciatura',
            new_name='licenciatura',
        ),
        migrations.RenameField(
            model_name='alumno',
            old_name='Nombre',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='Emocion',
            new_name='emocion',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='Texto_generado',
            new_name='texto_generado',
        ),
        migrations.CreateModel(
            name='aprendizaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipos_aprendizaje', models.CharField(max_length=40)),
                ('id_alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.alumno')),
            ],
        ),
    ]
