# Generated by Django 6.0.1 on 2026-01-25 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_estilos_aprendizaje_p1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estilos_aprendizaje',
            name='p1',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='estilos_aprendizaje',
            name='p10',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='estilos_aprendizaje',
            name='p2',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='estilos_aprendizaje',
            name='p3',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='estilos_aprendizaje',
            name='p4',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='estilos_aprendizaje',
            name='p5',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='estilos_aprendizaje',
            name='p6',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='estilos_aprendizaje',
            name='p7',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='estilos_aprendizaje',
            name='p8',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='estilos_aprendizaje',
            name='p9',
            field=models.CharField(max_length=1),
        ),
    ]
