# Generated by Django 5.2.7 on 2025-11-08 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_rename_apellido_materno_alumno_apellido_materno_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aprendizaje',
            name='id',
        ),
        migrations.AddField(
            model_name='aprendizaje',
            name='id_aprendizaje',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
