# Generated by Django 6.0.1 on 2026-01-25 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_estilos_aprendizaje_p1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estilos_aprendizaje',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estilosaprendizaje', to='catalog.alumno'),
        ),
    ]
