# Generated by Django 5.2.7 on 2025-11-10 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_remove_aprendizaje_id_aprendizaje_id_aprendizaje'),
    ]

    operations = [
        migrations.CreateModel(
            name='emocion',
            fields=[
                ('id_emocion', models.AutoField(primary_key=True, serialize=False)),
                ('emocion', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('rool', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='diccionario',
            fields=[
                ('id_palabras', models.AutoField(primary_key=True, serialize=False)),
                ('palabra', models.CharField(max_length=10)),
                ('id_emocion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.emocion')),
            ],
        ),
        migrations.CreateModel(
            name='reporte',
            fields=[
                ('id_reporte', models.AutoField(primary_key=True, serialize=False)),
                ('Resultado', models.CharField(max_length=45)),
                ('id_alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.alumno')),
                ('id_emocion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.emocion')),
            ],
        ),
        migrations.CreateModel(
            name='texto',
            fields=[
                ('id_texto', models.AutoField(primary_key=True, serialize=False)),
                ('contenido', models.CharField(max_length=1000)),
                ('id_emocion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.emocion')),
            ],
        ),
    ]
