# Generated by Django 5.2.7 on 2025-11-19 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_emocion_usuario_diccionario_reporte_texto'),
    ]

    operations = [
        migrations.CreateModel(
            name='estilos_aprendizaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p1', models.CharField(max_length=1)),
                ('p2', models.CharField(max_length=1)),
                ('p3', models.CharField(max_length=1)),
                ('p4', models.CharField(max_length=1)),
                ('p5', models.CharField(max_length=1)),
                ('p6', models.CharField(max_length=1)),
                ('p7', models.CharField(max_length=1)),
                ('p8', models.CharField(max_length=1)),
                ('p9', models.CharField(max_length=1)),
                ('p10', models.CharField(max_length=1)),
                ('resultado', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='alumno',
            name='tipo_aprendizaje',
            field=models.CharField(choices=[('visual', 'Visual'), ('auditivo', 'Auditivo'), ('kinestesico', 'Kinestésico')], default='visual', max_length=20),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='nombre',
            field=models.CharField(help_text='Ingrese tu nombre', max_length=30),
        ),
        migrations.DeleteModel(
            name='aprendizaje',
        ),
    ]
