# Generated by Django 5.2.7 on 2025-11-22 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_estilos_aprendizaje_alumno_tipo_aprendizaje_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstilosAprendizaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p1', models.CharField(max_length=1)),
                ('p2', models.CharField(max_length=1)),
                ('p3', models.CharField(max_length=1)),
                ('p4', models.CharField(max_length=1)),
                ('p5', models.CharField(max_length=1)),
                ('p6', models.CharField(max_length=1)),
                ('p7', models.CharField(max_length=1)),
                ('p8', models.CharField(max_length=1)),
                ('p9', models.CharField(max_length=1)),
                ('p10', models.CharField(max_length=1)),
                ('resultado', models.CharField(blank=True, max_length=50)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.alumno')),
            ],
        ),
        migrations.DeleteModel(
            name='estilos_aprendizaje',
        ),
        migrations.RenameField(
            model_name='diccionario',
            old_name='id_emocion',
            new_name='emocion',
        ),
        migrations.RenameField(
            model_name='reporte',
            old_name='id_alumno',
            new_name='alumno',
        ),
        migrations.RenameField(
            model_name='reporte',
            old_name='id_emocion',
            new_name='emocion',
        ),
        migrations.RenameField(
            model_name='reporte',
            old_name='Resultado',
            new_name='resultado',
        ),
        migrations.RenameField(
            model_name='texto',
            old_name='id_emocion',
            new_name='emocion',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='rool',
            new_name='rol',
        ),
        migrations.RemoveField(
            model_name='diccionario',
            name='id_palabras',
        ),
        migrations.RemoveField(
            model_name='emocion',
            name='id_emocion',
        ),
        migrations.RemoveField(
            model_name='reporte',
            name='id_reporte',
        ),
        migrations.RemoveField(
            model_name='texto',
            name='id_texto',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='id_usuario',
        ),
        migrations.AddField(
            model_name='diccionario',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='emocion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='reporte',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='texto',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
