# Generated by Django 5.2.7 on 2025-11-22 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_estilosaprendizaje_delete_estilos_aprendizaje_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='tipo_aprendizaje',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
